// Generated by CoffeeScript 1.4.0
(function() {
  var args, dat, events, fs, log, _;

  fs = require('fs');

  _ = require('underscore');

  args = process.argv.splice(2);

  dat = fs.readFileSync(args[0]).toString().split('\n');

  log = console.log;

  events = {};

  _(dat).each(function(line) {
    var o;
    if (line.length) {
      o = JSON.parse(line);
      if (!events[o.message]) {
        events[o.message] = [];
      }
      return events[o.message].push(o.duration);
    }
  });

  _(events).each(function(eventSet, event) {
    var avg, max, min;
    avg = 0;
    min = 1e9;
    max = -1e9;
    _(eventSet).each(function(duration) {
      avg += duration;
      if (duration < min) {
        min = duration;
      }
      if (duration > max) {
        return max = duration;
      }
    });
    avg /= eventSet.length;
    return log(event, 'avg:', avg, 'min:', min, 'max:', max, 'num', eventSet.length, 'total time', eventSet.length * avg);
  });

}).call(this);
